Разметка главной страницы
htmlacademy-htmlcss/1631929-sedona-31 pull request #2
Opened 2021-05-29 18:36 UTC by ivanushkovakarina

Выполнила первое задание 2 модуля

2021-05-30 11:04 UTC, antonova-elena requested changes
Карина, ты молодец 👍  Давай ещё немного поработаем над разметкой. Подробности в комментариях.

2021-05-31 19:16 UTC, ivanushkovakarina commented on blank.html
> +          <img src="https://via.placeholder.com/150x100" width="150" height="100" alt="Логотип">
Логотипом я посчитала цветное изображение, не включая голубой треугольник

2021-05-31 19:36 UTC, ivanushkovakarina commented on catalog.html
> +            </ul>
хочу уточнить, каким образом должно быть доведение “треугольников”: 
- по клику на треугольники изменяется порядок сортировки (тогда это две кнопки)
- треугольники не являются кнопками, а иконками, а клик на ссылку “по рейтингу” вызывает сортировку содержимого и “меняет” активную иконку треугольника

2021-07-12 09:49 UTC, antonova-elena commented
не актуален

2021-07-12 09:49 UTC, closed without merging